add Deno, fix NanaZip & rust-analyzer & CDI/CDM
mirrorz-org/genisolist pull request #1
Opened 2024-05-12 03:53 UTC by stackinspector

2024-05-12 11:12 UTC, Harry-Chen commented on includes/app/crystaldiskinfo.ini
> +listvers = 3
修改列出数量的目的是？

2024-05-12 11:16 UTC, Harry-Chen requested changes
感觉似乎有些匹配问题，是否考虑尝试使用 `rsync-stub-generator.py` 获得列表之后尝试运行脚本？

2024-05-12 11:16 UTC, Harry-Chen commented on includes/app/nanazip.ini
> +location = github-release/M2Team/NanaZip/*
这样应该是无法匹配带一层文件夹的路径的

2024-05-12 11:16 UTC, Harry-Chen commented on includes/app/deno.ini
> +location = github-release/denoland/deno/*
同上，应该无法匹配

2024-05-12 11:25 UTC, stackinspector commented on includes/app/crystaldiskinfo.ini
> +listvers = 3
观察到CDI每个版本有3个assets，CDM有2个。

2024-05-12 11:26 UTC, stackinspector commented on includes/app/nanazip.ini
> +location = github-release/M2Team/NanaZip/*
虽然没测试但是看懂了（）已修改

2024-05-12 16:13 UTC, stackinspector commented
给CDI/CDM加上了zip asserts的解析，同时避免解析src，另外再次修改了列出数量以符合加上zip后的asserts数量。

2024-05-14 07:32 UTC, Harry-Chen commented
@stackinspector 请 rebase，然后我可以合并

2024-05-14 07:52 UTC, Harry-Chen approved these changes
LGTM

2024-05-14 07:52 UTC, merged